services:
  kafka-connect:
    build:
      context: ./kafka-connect
      dockerfile: Dockerfile
    image: custom-kafka-connect
    hostname: kafka-connect
    container_name: kafka-connect
    depends_on:
      - clickhouse
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "<bootstrapserver>"
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect=DEBUG"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "TRACE"
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_SECURITY_PROTOCOL: "SASL_SSL"
      CONNECT_SASL_MECHANISM: "PLAIN"
      CONNECT_SASL_JAAS_CONFIG: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="<api-key>"
        password="<api-secret>";
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/home/appuser/clickhouse-kafka-connect-v1.1.3/lib"
    ports:
      - "8083:8083"
    # volumes:
    #   - ./connect-plugins:temp/home/appuser/clickhouse-kafka-connect-v1.1.3/lib
    entrypoint: ["/bin/bash", "-c", "while ! nc -z clickhouse 8123; do sleep 2; done; /etc/confluent/docker/run"]

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    hostname: clickhouse
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
     
volumes:
  clickhouse_data:
